[package]
name = "channel_telegram"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.7"
teloxide = { version = "0.15.0", features = ["macros"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
once_cell = "1.21.3"
libc = "0.2.172"
channel_plugin = { version = "0.1.0", path = "../channel_plugin" }
anyhow = "1.0.98"
chrono = { version = "0.4", features = ["serde"] }
schemars = { version = "0.8.22", features = ["chrono"] } 
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
dotenvy = "0.15.7"

[[bin]]
name = "channel_telegram"    # or "echo_bot", whatever you like
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
async-trait = "0.1.88"
typetag = "0.2.20"
serde = { version = "1.0.219", features = ["derive"] }
